modmap:
  - name: "Bracket Remap"
    remap:
      KEY_LEFTBRACE: LeftBrace
      KEY_RIGHTBRACE: RightBrace

keymap:
  - name: "Custom Symbols Key"
    remap:
      # Normal press for '<'
      KEY_BACKSLASH:
        with_layout:
          layout: us
          press: [Shift, Comma]

      # Shift press for '>'
      Shift-KEY_BACKSLASH:
        with_layout:
          layout: us
          press: [Shift, Period]

      # Right Alt press for '~'
      RAlt-KEY_BACKSLASH:
        with_layout:
          layout: us
          press: [Shift, Grave]

      # Shift + Right Alt press for '|'
      Shift-RAlt-KEY_BACKSLASH:
        with_layout:
          layout: us
          press: [Shift, Backslash]
